replicaCount: 1

image:
  repository: ghcr.io/windsource/gravivol
  #repository: gravivol-reg:5000/gravivol
  pullPolicy: IfNotPresent
  #pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# Here you can configure which PVCs should be handled by gravivol. 
# Format: "<namespace1>/<pvc1>,<namespace2>/<pvc2>,...""
# If the list is empty, all PVCs in all namespaces are handled
pvcConfig: ""

# See Rust log levels
rustLog: info

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

resources: {}

livenessProbe:
  httpGet:
    path: /health
    port: http
    scheme: HTTPS
readinessProbe:
  httpGet:
    path: /health
    port: http
    scheme: HTTPS

volumes:
  - name: cert-volume
    secret:
      secretName: gravivol-server-cert

volumeMounts:
  - name: cert-volume
    readOnly: true
    mountPath: "/certs/cert.pem"
    subPath: tls.crt
  - name: cert-volume
    readOnly: true
    mountPath: "/certs/key.pem"
    subPath: tls.key

nodeSelector: {}

tolerations: []

affinity: {}
