name: Build and Push Multi-platform Container

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    # We need an Ubuntu 24.04 runner as we copy a specific ubuntu.sources file
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.90.0
        with:
          targets: x86_64-unknown-linux-musl,aarch64-unknown-linux-musl

      - name: Install cross-compilation tools
        run: |
          cat <<EOF | sudo tee -a /etc/apt/sources.list.d/ubuntu.sources

          Types: deb
          URIs: http://ports.ubuntu.com/ubuntu-ports/
          Suites: noble noble-updates noble-backports
          Components: main universe restricted multiverse
          Architectures: arm64
          Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

          ## Ubuntu security updates. Aside from URIs and Suites,
          ## this should mirror your choices in the previous section.
          Types: deb
          URIs: http://ports.ubuntu.com/ubuntu-ports/
          Suites: noble-security
          Components: main universe restricted multiverse
          Architectures: arm64
          Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
          EOF

          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu musl-tools
          sudo dpkg --add-architecture arm64
          sudo apt update
          sudo apt install -y musl-tools:arm64

      - name: Unit tests
        run: |
          cargo test

      - name: Build binaries x86_64
        run: |
          cargo build --release --target x86_64-unknown-linux-musl
          mkdir -p dist/amd64
          cp target/x86_64-unknown-linux-musl/release/gravivol dist/amd64/

      - name: Build binaries arm64
        run: |
          cargo build --release --target aarch64-unknown-linux-musl
          mkdir -p dist/arm64
          cp target/aarch64-unknown-linux-musl/release/gravivol dist/arm64/
        env:
          CC: "/usr/bin/aarch64-linux-musl-gcc"
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER: aarch64-linux-gnu-gcc

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/windsource/gravivol
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}                

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
